// File generated by Gemini.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDalQQKQlRuLKQ8vyC6JbYFL3Rl5B1kWsI',
    appId: '1:71384070933:web:2b9a1799b07a750f2d071c',
    messagingSenderId: '71384070933',
    projectId: 'realtimefrb-27357',
    authDomain: 'realtimefrb-27357.firebaseapp.com',
    databaseURL: 'https://realtimefrb-27357-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'realtimefrb-27357.appspot.com', // CORRECTED VALUE
    measurementId: 'G-YQ88NJE2WF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCC7Mf95BdQoAtpVvURa81PxEHwU56pIKU',
    appId: '1:71384070933:android:4e4cb7c8f9e614c32d071c',
    messagingSenderId: '71384070933',
    projectId: 'realtimefrb-27357',
    databaseURL: 'https://realtimefrb-27357-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'realtimefrb-27357.appspot.com', // CORRECTED VALUE
  );
}
